# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language - Japanese
ja:
  languageCode: ja
  languageName: 日本語
  weight: 1
  title: Ryo Nakamuraのポートフォリオ
  contentDir: content/ja

# English
en:
  languageCode: en-us
  languageName: English
  weight: 2
  title: Ryo Nakamura's Portfolio
  contentDir: content/en

